// <auto-generated />
namespace Nebulus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddScreenSaverPresenterType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddScreenSaverPresenterType));
        
        string IMigrationMetadata.Id
        {
            get { return "201608121527192_AddScreenSaverPresenterType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
